name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ingestion/requirements.txt ]; then pip install -r ingestion/requirements.txt; fi
          if [ -f streamlit_app/requirements.txt ]; then pip install -r streamlit_app/requirements.txt; fi

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 ingestion glue_jobs streamlit_app --count --select=E9,F63,F7,F82 --show-source --statistics
